name: Airdrop Tokens

on:
  workflow_dispatch:

jobs:
  airdrop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Run Airdrop
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOYER_KEY }}
        run: python3 airdrop_sender.py
