name: Random Airdrop

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'   # Every 12 hours

jobs:
  random-airdrop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Send Random Airdrops
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOYER_KEY }}
        run: python3 random_airdrop.py
